import type { LessonExternalToolDefinition } from "../../types/externalTools";

const googleDomains = ["docs.google.com", "forms.gle"] as const;
const codapDomains = ["codap.concord.org"] as const;
const formSubmissionDomains = ["docs.google.com", "forms.gle"] as const;
const officialHistoryDomains = ["heritage.go.kr", "museum.go.kr", "unesco.org"] as const;

export const threeKingdomsExternalTools: readonly LessonExternalToolDefinition[] = [
  {
    lessonId: 1,
    toolId: "data-question",
    toolName: "문화유산 질문 만들기",
    purpose: "모둠과 문화유산을 선택하고, 사진에서 찾은 단서를 바탕으로 조사할 질문 한 문장을 완성합니다.",
    estimatedMinutes: 12,
    launchMode: "internal",
    studentUrl: "",
    embedUrl: "",
    teacherSourceUrl: "",
    submissionUrl: "",
    resultBoardUrl: "",
    resultKind: "none",
    resultGuide: "웹앱에 저장한 우리 모둠 질문 카드를 발표합니다.",
    steps: ["우리 모둠과 관찰할 문화유산을 선택합니다.", "사진에서 보이는 단서와 모을 데이터 항목을 고릅니다.", "관찰한 사실과 조사할 질문을 작성해 저장합니다."],
    dataTip: "왕 이름을 맞히는 질문보다 시기·지역·재료·발견 장소처럼 자료로 모을 수 있는 질문이 좋습니다.",
    allowedDomains: formSubmissionDomains,
  },
  {
    lessonId: 2,
    toolId: "sheets-schema",
    toolName: "학급 데이터 약속 만들기",
    purpose: "서로 다른 표를 비교하고, 공통 열 이름과 값 표기를 통일한 뒤 항목 관계 질문을 완성합니다.",
    estimatedMinutes: 20,
    launchMode: "internal",
    studentUrl: "",
    embedUrl: "",
    teacherSourceUrl: "",
    submissionUrl: "",
    resultBoardUrl: "",
    resultKind: "none",
    resultGuide: "웹앱에 저장된 우리 모둠 데이터 설계 카드를 발표합니다.",
    steps: ["열 이름이 다른 두 표를 비교합니다.", "학급 공통 항목과 표준값을 정합니다.", "항목 두 개를 연결해 비교 질문을 만들고 저장합니다."],
    dataTip: "유산 이름, 나라, 시대 범위, 정확한 연도, 발견 지역, 자료 종류, 확인된 사실, 출처는 모든 모둠이 같은 이름으로 사용합니다.",
    fallbackPath: "data/three-kingdoms/heritage-data-starter.csv",
    allowedDomains: formSubmissionDomains,
  },
  {
    lessonId: 3,
    toolId: "verification-five-steps",
    toolName: "검증 5단계 공동 연습",
    purpose: "국가기관 자료·블로그·AI 요약문에 출처·시기·교차·원본·보류를 적용합니다.",
    estimatedMinutes: 20,
    launchMode: "internal",
    studentUrl: "",
    embedUrl: "",
    teacherSourceUrl: "",
    submissionUrl: "",
    resultBoardUrl: "",
    resultKind: "none",
    resultGuide: "자료 3종 비교지와 검증 5단계 체크리스트에 근거를 기록합니다.",
    steps: ["출처와 작성 시기를 확인합니다.", "다른 자료와 교차하고 원본까지 이동합니다.", "확인하기 어려운 내용은 '아직 모름'으로 보류합니다."],
    dataTip: "공식 자료도 작성 시기와 근거를 확인하고 다른 자료와 교차합니다.",
    allowedDomains: officialHistoryDomains,
  },
  {
    lessonId: 4,
    toolId: "official-source-hub",
    toolName: "모둠별 공식 자료실",
    purpose: "국가유산청·국립박물관·유네스코 자료로 담당 유산의 조사 카드를 완성합니다.",
    estimatedMinutes: 27,
    launchMode: "internal",
    studentUrl: "",
    embedUrl: "",
    teacherSourceUrl: "",
    submissionUrl: "",
    resultBoardUrl: "",
    resultKind: "none",
    resultGuide: "유산 조사 카드와 출처 기록표에 확인한 내용과 아직 모르는 점을 남깁니다.",
    steps: ["담당 유산과 조사할 항목을 선택합니다.", "공식 자료를 읽고 확인한 사실을 자기 말로 씁니다.", "AI 오류·아직 모름·출처를 함께 점검합니다."],
    dataTip: "자료 문장을 통째로 베끼지 말고 확인한 범위만 짧게 바꾸어 씁니다.",
    allowedDomains: officialHistoryDomains,
  },
  {
    lessonId: 5,
    toolId: "google-sheets-cleaning",
    toolName: "Google Sheets · 역사 데이터 정제",
    toolHomeUrl: "https://docs.google.com/spreadsheets/u/0/",
    purpose: "웹앱 정제 연습으로 중복·빈칸·표기 차이를 고치는 규칙을 익힌 뒤, 모둠 시트의 실제 데이터를 같은 규칙으로 분석 가능한 CSV로 만듭니다.",
    estimatedMinutes: 28,
    launchMode: "new-tab",
    studentUrl: "https://docs.google.com/spreadsheets/u/0/",
    embedUrl: "",
    teacherSourceUrl: "",
    submissionUrl: "",
    resultBoardUrl: "",
    resultKind: "csv",
    resultGuide: "정제된 CSV와 무엇을 왜 고쳤는지 기록한 데이터 정제 기록지를 남깁니다.",
    steps: ["웹앱 정제 연습에서 여섯 가지 문제를 직접 해결합니다.", "오류가 심어진 연습 CSV를 Google Sheets로 불러와 같은 규칙으로 정리합니다.", "정제된 표를 CSV로 내려받습니다."],
    dataTip: "빈칸은 추측해 채우지 않고 ‘확인 필요’로 표시하며, 정확한 연도가 없는 시기는 범위 그대로 둡니다.",
    fallbackPath: "data/three-kingdoms/heritage-data-messy.csv",
    allowedDomains: [...googleDomains, ...formSubmissionDomains],
  },
  {
    lessonId: 6,
    toolId: "codap-chart",
    toolName: "CODAP · 역사 데이터 시각화",
    toolHomeUrl: "https://codap.concord.org/app/",
    purpose: "정리한 데이터를 연도·지역·종류별 그래프로 바꿉니다.",
    estimatedMinutes: 25,
    launchMode: "embed",
    studentUrl: "https://codap.concord.org/app/",
    embedUrl: "https://codap.concord.org/app/",
    teacherSourceUrl: "",
    submissionUrl: "",
    resultBoardUrl: "",
    resultKind: "png",
    resultGuide: "축 이름과 제목이 보이도록 그래프를 PNG로 저장합니다.",
    steps: ["정리된 CSV 또는 60행 학급 예비 데이터셋을 CODAP에 불러옵니다.", "가로축과 세로축에 비교할 항목을 놓습니다.", "그래프 제목과 단위를 확인한 뒤 저장합니다."],
    dataTip: "그래프는 예쁘게 꾸미는 그림이 아니라 무엇과 무엇을 비교했는지 보여 주는 자료입니다.",
    fallbackPath: "data/three-kingdoms/heritage-data-full.csv",
    allowedDomains: [...codapDomains, ...formSubmissionDomains],
  },
  {
    lessonId: 7,
    toolId: "codap-interpretation",
    toolName: "CODAP · 그래프 해석",
    toolHomeUrl: "https://codap.concord.org/app/",
    purpose: "그래프가 말해 주는 점과 그래프만으로는 알 수 없는 점을 나눕니다.",
    estimatedMinutes: 22,
    launchMode: "embed",
    studentUrl: "https://codap.concord.org/app/",
    embedUrl: "https://codap.concord.org/app/",
    teacherSourceUrl: "",
    submissionUrl: "",
    resultBoardUrl: "",
    resultKind: "link",
    resultGuide: "그래프 링크와 ‘보이는 점·모르는 점’ 해석 문장을 함께 제출합니다.",
    steps: ["가장 큰 값과 작은 값을 찾습니다.", "자료가 모인 경향을 한 문장으로 말합니다.", "그래프만으로 단정할 수 없는 내용을 따로 적습니다."],
    dataTip: "자료 수가 적거나 특정 지역 자료만 많다면 전체 삼국시대의 모습으로 일반화하지 않습니다.",
    fallbackPath: "data/three-kingdoms/heritage-data-full.csv",
    allowedDomains: [...codapDomains, ...formSubmissionDomains],
  },
  {
    lessonId: 8,
    toolId: "codap-inference",
    toolName: "CODAP · 과거 유추",
    toolHomeUrl: "https://codap.concord.org/app/",
    purpose: "두 가지 이상의 데이터 관계를 근거로 옛사람의 생활과 교류를 유추합니다.",
    estimatedMinutes: 24,
    launchMode: "embed",
    studentUrl: "https://codap.concord.org/app/",
    embedUrl: "https://codap.concord.org/app/",
    teacherSourceUrl: "",
    submissionUrl: "",
    resultBoardUrl: "",
    resultKind: "png",
    resultGuide: "관계 그래프와 ‘근거 2개 → 유추 1개’ 문장을 제출합니다.",
    steps: ["서로 관계가 있을 것 같은 항목 두 개를 고릅니다.", "그래프에서 반복되거나 함께 나타나는 모습을 찾습니다.", "근거 두 개를 먼저 말한 뒤 가능한 과거 모습을 유추합니다."],
    dataTip: "유추는 상상이 아닙니다. 자료가 보여 주는 범위까지만 ‘~했을 가능성이 있다’라고 말합니다.",
    fallbackPath: "data/three-kingdoms/heritage-data-full.csv",
    allowedDomains: [...codapDomains, "app.rawgraphs.io", ...formSubmissionDomains],
    helperLinks: [{ label: "관계 그래프 확장 · RAWGraphs", href: "https://app.rawgraphs.io/" }],
  },
  {
    lessonId: 9,
    toolId: "ar-data-explanation",
    toolName: "AR 데이터 해설 체험실",
    purpose: "CODAP 그래프의 경향과 검증한 역사 사실을 AR 장면과 30초 도슨트 해설로 연결합니다.",
    estimatedMinutes: 29,
    launchMode: "internal",
    studentUrl: "",
    embedUrl: "",
    teacherSourceUrl: "",
    submissionUrl: "",
    resultBoardUrl: "",
    resultKind: "none",
    resultGuide: "AR 데이터 해설 기획서와 30초 도슨트 대본을 완성합니다.",
    steps: ["담당 유산의 AR 또는 대체 체험을 실행합니다.", "그래프 경향과 공식 자료의 사실을 한 장면에 연결합니다.", "자료의 한계를 포함한 30초 해설을 연습합니다."],
    dataTip: "그래프는 경향을, AR은 유산의 특징을 보여 줍니다. 두 자료가 같은 근거를 가리켜야 합니다.",
    allowedDomains: formSubmissionDomains,
  },
  {
    lessonId: 10,
    toolId: "ar-data-museum",
    toolName: "AR 데이터 박물관",
    purpose: "수집·정제한 자료, 그래프, 해석과 과거 유추를 AR 문화유산 해설과 한 흐름으로 보여 줍니다.",
    estimatedMinutes: 30,
    launchMode: "internal",
    studentUrl: "",
    embedUrl: "",
    teacherSourceUrl: "",
    submissionUrl: "",
    resultBoardUrl: "",
    resultKind: "none",
    resultGuide: "관람객에게 그래프 한 장과 근거 있는 역사 해설을 함께 설명합니다.",
    steps: ["우리 모둠 결과 링크와 AR 카드를 엽니다.", "그래프의 경향과 과거 유추를 설명합니다.", "자료의 범위와 아직 모르는 점을 말하고 질문을 받습니다."],
    dataTip: "AR이 멈춰도 그래프와 해설만으로 수업이 이어지도록 결과 PNG와 QR 대체 경로를 준비합니다.",
    allowedDomains: formSubmissionDomains,
  },
];

export function getThreeKingdomsExternalTool(lessonId: number) {
  return threeKingdomsExternalTools.find((tool) => tool.lessonId === lessonId) ?? threeKingdomsExternalTools[0];
}
