import type { LessonExternalToolDefinition } from "../../types/externalTools";

const googleDomains = ["docs.google.com", "forms.gle"] as const;
const codapDomains = ["codap.concord.org"] as const;
const formSubmissionDomains = ["docs.google.com", "forms.gle"] as const;

export const threeKingdomsExternalTools: readonly LessonExternalToolDefinition[] = [
  {
    lessonId: 1,
    toolId: "data-question",
    toolName: "유산 데이터 질문판",
    purpose: "여섯 문화유산을 관찰하고 우리 모둠이 모을 데이터 질문을 하나 정합니다.",
    estimatedMinutes: 12,
    launchMode: "internal",
    studentUrl: "",
    embedUrl: "",
    teacherSourceUrl: "",
    submissionUrl: "",
    resultBoardUrl: "",
    resultKind: "none",
    resultGuide: "모둠에서 정한 질문은 활동지에 한 문장으로 남깁니다.",
    steps: ["유산 사진에서 눈에 보이는 특징을 말합니다.", "서로 비교하려면 어떤 정보가 필요한지 생각합니다.", "가장 궁금한 질문 하나를 모둠에서 정합니다."],
    dataTip: "왕 이름을 맞히는 질문보다 시기·지역·재료·발견 장소처럼 자료로 모을 수 있는 질문이 좋습니다.",
    allowedDomains: formSubmissionDomains,
  },
  {
    lessonId: 2,
    toolId: "sheets-schema",
    toolName: "Google Sheets · 데이터 설계표",
    toolHomeUrl: "https://docs.google.com/spreadsheets/",
    purpose: "모든 모둠이 함께 사용할 데이터 항목과 항목 사이의 관계를 정합니다.",
    estimatedMinutes: 20,
    launchMode: "new-tab",
    studentUrl: "",
    embedUrl: "",
    teacherSourceUrl: "",
    submissionUrl: "",
    resultBoardUrl: "",
    resultKind: "link",
    resultGuide: "완성한 모둠 데이터 설계표의 공유 링크를 제출합니다.",
    steps: ["예시 표의 열 이름을 읽습니다.", "비교에 꼭 필요한 항목과 필요 없는 항목을 나눕니다.", "시기·지역·자료 종류가 어떻게 연결되는지 화살표로 설명합니다."],
    dataTip: "시기, 지역, 자료 종류, 확인된 사실, 출처는 여섯 모둠이 똑같은 이름으로 사용합니다.",
    fallbackPath: "data/three-kingdoms/heritage-data-starter.csv",
    allowedDomains: googleDomains,
    setupRequired: true,
  },
  {
    lessonId: 3,
    toolId: "forms-practice",
    toolName: "Google Forms · 수집 연습",
    toolHomeUrl: "https://docs.google.com/forms/",
    purpose: "믿을 수 있는 출처와 정확한 수집 방법을 연습합니다.",
    estimatedMinutes: 18,
    launchMode: "embed",
    studentUrl: "",
    embedUrl: "",
    teacherSourceUrl: "",
    submissionUrl: "",
    resultBoardUrl: "",
    resultKind: "link",
    resultGuide: "연습 응답을 제출한 뒤 모둠끼리 같은 자료가 같은 방식으로 기록됐는지 확인합니다.",
    steps: ["자료를 만든 기관과 주소를 먼저 확인합니다.", "확인된 사실과 해석을 다른 칸에 씁니다.", "정확히 알 수 없는 내용은 판단 보류로 표시합니다."],
    dataTip: "출처가 없는 이미지와 AI 요약문은 원자료가 아닙니다. 원문이나 기관 설명으로 다시 확인합니다.",
    allowedDomains: googleDomains,
    setupRequired: true,
  },
  {
    lessonId: 4,
    toolId: "forms-collection",
    toolName: "Google Forms · 모둠 자료 수집",
    toolHomeUrl: "https://docs.google.com/forms/",
    purpose: "담당 유산 자료를 같은 형식으로 12~20건 모읍니다.",
    estimatedMinutes: 28,
    launchMode: "embed",
    studentUrl: "",
    embedUrl: "",
    teacherSourceUrl: "",
    submissionUrl: "",
    resultBoardUrl: "",
    resultKind: "link",
    resultGuide: "응답 시트에서 우리 모둠 코드로 필터링한 공유 링크를 남깁니다.",
    steps: ["공식 기관 자료에서 필요한 정보를 찾습니다.", "한 자료를 한 번만 입력합니다.", "모둠원이 입력한 자료 수와 출처를 함께 확인합니다."],
    dataTip: "학생 이름 대신 1모둠~6모둠 코드만 사용하고 공개 폼에는 개인정보를 넣지 않습니다.",
    fallbackPath: "data/three-kingdoms/heritage-data-starter.csv",
    allowedDomains: googleDomains,
    setupRequired: true,
  },
  {
    lessonId: 5,
    toolId: "sheets-cleanup",
    toolName: "Google Sheets · 데이터 전처리",
    toolHomeUrl: "https://docs.google.com/spreadsheets/",
    purpose: "중복, 빈칸, 서로 다른 표기를 찾아 데이터를 깨끗하게 다듬습니다.",
    estimatedMinutes: 25,
    launchMode: "new-tab",
    studentUrl: "",
    embedUrl: "",
    teacherSourceUrl: "",
    submissionUrl: "",
    resultBoardUrl: "",
    resultKind: "csv",
    resultGuide: "정리된 시트를 CSV로 내려받거나 공유 링크를 제출합니다.",
    steps: ["같은 자료가 두 번 들어간 행을 찾습니다.", "빈칸과 오탈자를 고치고 항목 표기를 통일합니다.", "고친 이유를 전처리 기록 칸에 남깁니다."],
    dataTip: "‘경주’와 ‘경주시’, ‘6세기’와 ‘서기 500년대’처럼 같은 뜻의 표기는 하나로 맞춥니다.",
    fallbackPath: "data/three-kingdoms/heritage-data-starter.csv",
    allowedDomains: googleDomains,
    setupRequired: true,
  },
  {
    lessonId: 6,
    toolId: "codap-chart",
    toolName: "CODAP · 역사 데이터 시각화",
    toolHomeUrl: "https://codap.concord.org/app/",
    purpose: "정리한 데이터를 연도·지역·종류별 그래프로 바꿉니다.",
    estimatedMinutes: 25,
    launchMode: "embed",
    studentUrl: "https://codap.concord.org/app/",
    embedUrl: "https://codap.concord.org/app/",
    teacherSourceUrl: "",
    submissionUrl: "",
    resultBoardUrl: "",
    resultKind: "png",
    resultGuide: "축 이름과 제목이 보이도록 그래프를 PNG로 저장합니다.",
    steps: ["정리된 CSV를 CODAP에 불러옵니다.", "가로축과 세로축에 비교할 항목을 놓습니다.", "그래프 제목과 단위를 확인한 뒤 저장합니다."],
    dataTip: "그래프는 예쁘게 꾸미는 그림이 아니라 무엇과 무엇을 비교했는지 보여 주는 자료입니다.",
    fallbackPath: "data/three-kingdoms/heritage-data-starter.csv",
    allowedDomains: [...codapDomains, ...formSubmissionDomains],
  },
  {
    lessonId: 7,
    toolId: "codap-interpretation",
    toolName: "CODAP · 그래프 해석",
    toolHomeUrl: "https://codap.concord.org/app/",
    purpose: "그래프가 말해 주는 점과 그래프만으로는 알 수 없는 점을 나눕니다.",
    estimatedMinutes: 22,
    launchMode: "embed",
    studentUrl: "https://codap.concord.org/app/",
    embedUrl: "https://codap.concord.org/app/",
    teacherSourceUrl: "",
    submissionUrl: "",
    resultBoardUrl: "",
    resultKind: "link",
    resultGuide: "그래프 링크와 ‘보이는 점·모르는 점’ 해석 문장을 함께 제출합니다.",
    steps: ["가장 큰 값과 작은 값을 찾습니다.", "자료가 모인 경향을 한 문장으로 말합니다.", "그래프만으로 단정할 수 없는 내용을 따로 적습니다."],
    dataTip: "자료 수가 적거나 특정 지역 자료만 많다면 전체 삼국시대의 모습으로 일반화하지 않습니다.",
    fallbackPath: "data/three-kingdoms/heritage-data-starter.csv",
    allowedDomains: [...codapDomains, ...formSubmissionDomains],
  },
  {
    lessonId: 8,
    toolId: "codap-inference",
    toolName: "CODAP · 과거 유추",
    toolHomeUrl: "https://codap.concord.org/app/",
    purpose: "두 가지 이상의 데이터 관계를 근거로 옛사람의 생활과 교류를 유추합니다.",
    estimatedMinutes: 24,
    launchMode: "embed",
    studentUrl: "https://codap.concord.org/app/",
    embedUrl: "https://codap.concord.org/app/",
    teacherSourceUrl: "",
    submissionUrl: "",
    resultBoardUrl: "",
    resultKind: "png",
    resultGuide: "관계 그래프와 ‘근거 2개 → 유추 1개’ 문장을 제출합니다.",
    steps: ["서로 관계가 있을 것 같은 항목 두 개를 고릅니다.", "그래프에서 반복되거나 함께 나타나는 모습을 찾습니다.", "근거 두 개를 먼저 말한 뒤 가능한 과거 모습을 유추합니다."],
    dataTip: "유추는 상상이 아닙니다. 자료가 보여 주는 범위까지만 ‘~했을 가능성이 있다’라고 말합니다.",
    fallbackPath: "data/three-kingdoms/heritage-data-starter.csv",
    allowedDomains: [...codapDomains, "app.rawgraphs.io", ...formSubmissionDomains],
    helperLinks: [{ label: "관계 그래프 확장 · RAWGraphs", href: "https://app.rawgraphs.io/" }],
  },
  {
    lessonId: 9,
    toolId: "desmos-forecast",
    toolName: "Desmos · 미래 변화 예측",
    toolHomeUrl: "https://www.desmos.com/calculator?lang=ko",
    purpose: "연도별 수치의 흐름을 보고 보존·관람·디지털 이용의 미래를 조심스럽게 예측합니다.",
    estimatedMinutes: 25,
    launchMode: "new-tab",
    studentUrl: "https://www.desmos.com/calculator?lang=ko",
    embedUrl: "",
    teacherSourceUrl: "",
    submissionUrl: "",
    resultBoardUrl: "",
    resultKind: "png",
    resultGuide: "기본·좋은 조건·나쁜 조건의 세 예측과 가정·한계를 한 화면에 담습니다.",
    steps: ["연도와 수치를 표에 입력합니다.", "추세선을 보고 세 가지 미래 시나리오를 만듭니다.", "예측이 달라질 수 있는 조건과 한계를 적습니다."],
    dataTip: "미래의 역사적 사건을 맞히는 활동이 아닙니다. 보존 상태나 이용 수치의 변화를 조건에 따라 예측합니다.",
    fallbackPath: "data/three-kingdoms/heritage-trend-starter.csv",
    allowedDomains: ["desmos.com", "www.desmos.com", ...formSubmissionDomains],
  },
  {
    lessonId: 10,
    toolId: "ar-data-museum",
    toolName: "AR 데이터 박물관",
    purpose: "수집한 자료, 그래프, 해석, 예측을 AR 문화유산 해설과 한 흐름으로 보여 줍니다.",
    estimatedMinutes: 30,
    launchMode: "internal",
    studentUrl: "",
    embedUrl: "",
    teacherSourceUrl: "",
    submissionUrl: "",
    resultBoardUrl: "",
    resultKind: "none",
    resultGuide: "관람객에게 그래프 한 장과 근거 있는 역사 해설을 함께 설명합니다.",
    steps: ["우리 모둠 결과 링크와 AR 카드를 엽니다.", "그래프의 경향과 과거 유추를 설명합니다.", "미래 예측의 조건과 한계를 말하고 질문을 받습니다."],
    dataTip: "AR이 멈춰도 그래프와 해설만으로 수업이 이어지도록 결과 PNG와 QR 대체 경로를 준비합니다.",
    allowedDomains: formSubmissionDomains,
  },
];

export function getThreeKingdomsExternalTool(lessonId: number) {
  return threeKingdomsExternalTools.find((tool) => tool.lessonId === lessonId) ?? threeKingdomsExternalTools[0];
}
