import type { HeritageGroup } from "../../types/curriculum";

export const threeKingdomsGroups = [
  {
    id: 1,
    heritage: "무령왕릉",
    category: "백제",
    inquiryQuestion: "발굴은 왜 아쉬움으로 남았을까?",
    colorName: "보라",
    color: "#76538d",
    visualCue: "벽돌무덤의 아치와 출토 유물의 배치를 활용해 표현합니다.",
  },
  {
    id: 2,
    heritage: "백제 금동대향로",
    category: "백제",
    inquiryQuestion: "향로에 새겨진 것은 무엇을 뜻할까?",
    colorName: "초록",
    color: "#3d7667",
    visualCue: "연꽃, 산봉우리, 봉황의 비대칭 윤곽을 살려 표현합니다.",
  },
  {
    id: 3,
    heritage: "첨성대",
    category: "신라",
    inquiryQuestion: "첨성대는 정말 천문대였을까?",
    colorName: "남색",
    color: "#344f78",
    visualCue: "돌의 층과 별자리 무늬를 함께 사용하되 용도는 단정하지 않습니다.",
  },
  {
    id: 4,
    heritage: "신라 금관",
    category: "신라",
    inquiryQuestion: "금관은 실제로 쓰고 다녔을까?",
    colorName: "금색",
    color: "#ae7f26",
    visualCue: "나뭇가지형 세움 장식과 굽은옥을 강한 명암으로 표현합니다.",
  },
  {
    id: 5,
    heritage: "고구려 고분벽화",
    category: "고구려",
    inquiryQuestion: "벽화는 무엇을 그린 것일까?",
    colorName: "붉은갈색",
    color: "#8b4b3f",
    visualCue: "생활 모습과 사신도의 선을 굵고 비대칭적으로 구성합니다.",
    alternative: "학교 여건에 따라 충주 고구려비로 대체할 수 있습니다.",
  },
  {
    id: 6,
    heritage: "가야 고분군",
    category: "가야",
    inquiryQuestion: "가야는 왜 오랫동안 잊혔을까?",
    colorName: "주황",
    color: "#bd6834",
    visualCue: "능선 위 고분의 배열과 철기 유물의 형태를 함께 표현합니다.",
  },
] as const satisfies readonly HeritageGroup[];
