import { lazy, Suspense, useState } from 'react';
import { heritageImageUrl } from '../../content/heritageCatalog';
import NarrationEditor from '../../components/NarrationEditor';
import type { ExhibitionSound } from '../../lib/ar/sound';
import { newPoint, newQuestion, submissionProblems, type StudioProject, type StudioQuestion } from './project';
const HeritageModelView = lazy(() => import('../../components/HeritageModelView'));
export function NarrationStep({ project, onChange, onBusy, sound, onNext }: { project: StudioProject; onChange: (p: StudioProject) => void; onBusy: (busy: boolean) => void; sound: ExhibitionSound; onNext: () => void }) {
  const [selected, setSelected] = useState(project.ar.points[0].id);
  const [busy, setBusy] = useState(false);
  const point = project.ar.points.find(p => p.id === selected) || project.ar.points[0];
  function update(patch: Partial<typeof point>) { onChange({ ...project, ar: { ...project.ar, points: project.ar.points.map(p => p.id === point.id ? { ...p, ...patch } : p) } }); }
  return <section><header><h1>내 모형에 설명과 목소리를 붙여요</h1><p>사진에서 확인한 내용을 3~4곳에 나누어 설명해요.</p></header><div className="studio-narration-layout"><div><Suspense fallback={<p>모형을 불러와요…</p>}><HeritageModelView model={project.ar.model} image={heritageImageUrl('three-kingdoms', project.heritageId)} points={project.ar.points} selectedId={point.id} onSelect={id => { if (!busy) setSelected(id); }} onPlace={busy ? undefined : position => { update({ position }); }} targetIndex={project.heritageId - 1} /></Suspense><p>설명을 고른 뒤 모형의 해당 부분을 짧게 눌러 위치를 정해요.</p><label className="studio-check"><input type="checkbox" disabled={busy} checked={project.pointsChecked} onChange={e => onChange({ ...project, pointsChecked: e.target.checked })} />설명점 위치를 모두 확인했어요.</label></div><div className="studio-editor-fields"><div className="studio-tabs">{project.ar.points.map((p, i) => <button disabled={busy} aria-pressed={p.id === point.id} key={p.id} onClick={() => { setSelected(p.id); sound.narration(false); }}>해설 {i + 1}</button>)}{project.ar.points.length < 4 && <button disabled={busy} onClick={() => { const p = newPoint(3); onChange({ ...project, pointsChecked: false, ar: { ...project.ar, points: [...project.ar.points, p] } }); setSelected(p.id); }}>+ 해설 추가</button>}</div><fieldset disabled={busy}><label>설명할 곳<input maxLength={80} value={point.title} onChange={e => update({ title: e.target.value })} placeholder="예: 가운데 창" /></label><label>자료에서 확인한 설명<textarea rows={4} maxLength={1500} value={point.text} onChange={e => update({ text: e.target.value })} placeholder="조사한 근거 문장을 읽기 쉬운 말로 적어요." /></label></fieldset><NarrationEditor key={point.id} value={point.narration} onChange={narration => update({ narration })} onBusy={value => { setBusy(value); onBusy(value); sound.recordingActive(value); }} onPlayback={active => sound.narration(active)} />{project.ar.points.length > 3 && <button disabled={busy} onClick={() => { if (!window.confirm('선택한 해설과 녹음을 지울까요?')) return; const points = project.ar.points.filter(p => p.id !== point.id); onChange({ ...project, pointsChecked: false, ar: { ...project.ar, points, answerId: points[0].id }, questions: project.questions.map(q => q.pointId === point.id ? { ...q, pointId: points[0].id } : q) }); }}>이 해설 지우기</button>}</div></div><div className="studio-actions"><button className="studio-primary" disabled={busy} onClick={onNext}>문제 만들기 →</button></div></section>;
}
export function QuestionStep({ project, onChange, onSubmit, busy, connected, showSubmission = true }: { project: StudioProject; onChange: (p: StudioProject) => void; onSubmit: () => void; busy: boolean; connected: boolean; showSubmission?: boolean }) {
  function update(id: string, patch: Partial<StudioQuestion>) { onChange({ ...project, questions: project.questions.map(q => q.id === id ? { ...q, ...patch } : q) }); }
  const problems = submissionProblems(project);
  return <section><header><h1>해설을 들으면 풀 수 있는 문제</h1><p>모둠당 2~3문제 · 각 문제는 서로 다른 보기 3개와 정답 하나</p></header>{project.questions.map((q, index) => <fieldset className="studio-question-editor" disabled={busy} key={q.id}><legend>문제 {index + 1}</legend><label>친구에게 묻고 싶은 것<input maxLength={300} value={q.prompt} onChange={e => update(q.id, { prompt: e.target.value })} placeholder="해설에서 답을 찾을 수 있나요?" /></label><div className="studio-options">{q.options.map((option, i) => <label key={i}><span><input type="radio" name={`answer-${q.id}`} checked={q.answer === i} onChange={() => update(q.id, { answer: i })} />{i + 1}번 {q.answer === i ? '· 정답' : ''}</span><input aria-label={`${index + 1}번 문제 보기 ${i + 1}`} maxLength={150} value={option} onChange={e => update(q.id, { options: q.options.map((o, n) => n === i ? e.target.value : o) as [string, string, string] })} /></label>)}</div><label>답을 확인할 해설<select value={q.pointId} onChange={e => update(q.id, { pointId: e.target.value })}>{project.ar.points.map((p, i) => <option key={p.id} value={p.id}>해설 {i + 1} · {p.title || '제목을 입력하세요'}</option>)}</select></label>{project.questions.length > 2 && <button onClick={() => onChange({ ...project, questions: project.questions.filter(item => item.id !== q.id) })}>이 문제 지우기</button>}</fieldset>)}{project.questions.length < 3 && <button disabled={busy} onClick={() => onChange({ ...project, questions: [...project.questions, newQuestion(project.ar.points[0].id)] })}>+ 문제 한 개 더 만들기</button>}{showSubmission && <div className="studio-submit"><h2>제출 전 확인</h2>{problems.length ? <ul>{problems.map(message => <li key={message}>{message}</li>)}</ul> : <p>모형·해설·문제를 준비했어요. 제출하면 선생님이 전시를 시작할 수 있어요.</p>}<button className="studio-primary" disabled={busy || problems.length > 0 || !connected} onClick={onSubmit}>{busy ? '작품을 보내는 중…' : '모둠 작품 제출'}</button>{!connected && <p>수업코드로 입장하고, 선생님께 이 태블릿을 모둠 제출 담당으로 지정해 달라고 해 주세요.</p>}</div>}</section>;
}
